version: '3.8'
services:
  backend:
    restart: unless-stopped
    build:
      context: ./backend
    entrypoint: ./entrypoint.sh
    command: python3 main.py
    ports:
      - 8080:8080
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_PORT
      - PROJECT_DB
      - PROJECT_HOST=0.0.0.0
    depends_on:
      - db

  db:
    restart: unless-stopped
    build:
      context: ./db
    ports:
      - 5432:5432
    volumes:
       - postgresdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
      - POSTGRES_DB

volumes:
  postgresdata: