version: '3.8'
services:
  backend:
    restart: unless-stopped
    volumes:
      - ./backend/:/app/
    build:
      context: ./backend
    entrypoint: ./entrypoint.sh
    command: python3 main.py
    ports:
      - 8080:${PROJECT_PORT}
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_PORT
      - PROJECT_NAME
      - PROJECT_HOST=0.0.0.0
      - PROJECT_PORT
      - PROJECT_DB
      - JWT_SECRET_KEY
      - JWT_LIFETIME_SECS
      - MEDIA_ROOT
      - STORAGE_HASH_FILENAME
      - STORAGE_CHUNK_SIZE
      - CACHE_URL
    depends_on:
      - db

  db:
    restart: unless-stopped
    build:
      context: ./db
    ports:
      - 55432:${POSTGRES_PORT}
    volumes:
       - postgresdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
      - POSTGRES_DB

  redis:
    restart: always
    image: redis:7.0-alpine
    volumes:
      - redisdata:/data

volumes:
  postgresdata:
  redisdata: